package lexer;

public enum TokenType {
    EOF, IDENT, NUMBER, STRING, BOOL,

    INT, REAL, TEXT, BOOL_TYPE,

    LET, IF, ELSE, FOR, IN, INPUT, PRINT,

    PLUS, MINUS, STAR, SLASH,
    EQ, EQEQ, NOTEQ, GT, GTEQ, LT, LTEQ,
    COLON, DOTS, LPAREN, RPAREN, LBRACE, RBRACE, COMMA,

    UNKNOWN
}
